### ISSUE TITLE
Elm-effects are deprecated

### ISSUE THREAD

**Issue by mikeon** [CultivateHQ/seat_saver#15]
Hi, I saw opened issue about signals, so part 8 of tutorial seems to be no longer valid. 
https://github.com/evancz/elm-effects

Thanks for excellent tutorial!

**Comment by urfolomeus** [comment]
Thanks, yes I'll be removing it as soon as I have some spare time :)

**Comment by crenwick** [comment]
Hi, @urfolomeus -- adding this comment here because it seems somewhat relevant.

I recently went through your tutorials (great, btw!) to learn Elm + Phoenix channels. However, because Elm has had some breaking changes, I split off from your tutorials past the Phoenix channels tutorial.

The result is this: https://github.com/crenwick/seat_saver

Instead of using ports into `socket.js`, I imported the [elm-phoenix-socket](http://package.elm-lang.org/packages/fbonetti/elm-phoenix-socket/2.0.0) package and wired up the application with subscriptions. 

Feel free to check out it out in case you were looking into modernizing this repo/tutorial. [The Elm code](https://github.com/crenwick/seat_saver/blob/master/web/elm/SeatSaver.elm) is the main deviation from yours.

**Comment by urfolomeus** [comment]
Thanks for sharing @crenwick, and apologies for the delay in reply. I'll take a look at that later today :)

**Comment by urfolomeus** [comment]
@crenwick this is a really elegant solution. I don't fully grok how elm-phoenix-socket is working yet but will dive in to that in more detail over the weekend. Thanks so much for sharing this.

Would you mind if I referenced your version when I come to update my remaining posts?

**Comment by crenwick** [comment]
Thanks for the kind remarks, @urfolomeus! Yes, please, reference away (also, let me know when the new posts are up).

**Comment by urfolomeus** [comment]
Will do 😁

**Comment by urfolomeus** [comment]
@crenwick just fyi I've been signed off work for a while. Slowly getting back into things but there will be a bit of a delay still until I'm able to get the rest of the posts updated.

**Comment by urfolomeus** [comment]
@mikeon @crenwick I'm trying to consolidate these issues to one place. As such I'm going to close this in favour of https://github.com/CultivateHQ/seat_saver-017/issues/1.
